#!/bin/bash

while true; do
read line
echo "$line" > pipe
if [[ "$line" == "QUIT" ]]
then
exit 1
elif [[ ("$line" != "*") && ("$line" != "+") && !("$line" =~([0-9]+)) ]]
then
echo "ERROR of Input"
exit 1
fi
done
